const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_BLOGPOSTS: 'FETCH_BLOGPOSTS',
    FETCH_BLOGPOST: 'FETCH_BLOGPOST',
    SET_BLOGPOST: 'SET_BLOGPOST',
    SET_COMMENT: 'SET_COMMENT'
}

export default Constants;